version: '3.8'

services:
  back:
      image: 'docker-spring-boot-postgres:latest'
      container_name: back
      volumes:
        - ./back:/app/back
      working_dir: '/app/back'
      depends_on:
        - db
      environment:
        - POSTGRES_USER=$DB_USERNAME
        - POSTGRES_PASSWORD=$DB_PASSWORD
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/$DB_NAME
        - SPRING_DATASOURCE_USERNAME=$DB_USERNAME
        - SPRING_DATASOURCE_PASSWORD=$DB_PASSWORD
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      ports:
        - "8080:8086"
  front:
    image: 'node:lts-alpine'
    container_name: front
    volumes:
      - ./front:/app/front
    working_dir: '/app/front'
    entrypoint: ['npm', 'run', 'serve']
    ports:
      - "3000:8080"
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - "3306:3306"
      
volumes:
  db-volume: