version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: ./back
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/$DB_NAME
      - SPRING_DATASOURCE_USERNAME=$DB_USERNAME
      - SPRING_DATASOURCE_PASSWORD=$DB_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8086"
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - "3306:3306"
      
volumes:
  db-volume: